;; //////////////////////////////////////////////////////////////////
;; File    : bananatel.module
;; Desc    : INHABITANTS OF THE EARTH!
;; 
;; 

[global]

Name			= BananaTel
Description		= INHABITANTS OF THE EARTH!
DllName			= bananatel
LocaleFolder	= bananatel
ModFolder		= bananatel
ModVersion      = 9.9.2
PatcherUrl		= 

;; //////////////////////////////////////////////////////////////////
;; List of archives to load for this MOD order is important
;; The first Archives registered will be scanned for files first

ArchiveFile_3= TellurianData.sga
ArchiveFile_2= InsectData.sga
ArchiveFile_1= bananatel.sga
;; //////////////////////////////////////////////////////////////////
;; List of MODs that have might have scenario packs that are 
;; compatible with this MOD.  Will only work if the scenarios are
;; In a scenario pack.
CompatableMod_1 = IC